language: node_js
node_js:
- 14.15.4
cache: npm 

install:
  - npm ci

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: backend
  on:
    branch: master